---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/checkmarx
    tag: "latest"

inputs:
  - name: git-repo

run:
  path: git-repo/ci/tasks/checkmarx.sh

params:
  host: ((host))
  username: ((username))
  password: ((password))
  project: ((project))
  locationType: ((locationType))
  locationPath: ((locationPath))
