resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/bbyers-pivotal/willitconnect.git
    branch: master

jobs:
  - name: checkmarx
    plan:
    - get: git-repo
      trigger: true
    - task: checkmarx
      file: git-repo/ci/tasks/checkmarx.yml
      params:
        host: ((host))
        username: ((username))
        password: ((password))
        project: ((project))
        locationType: ((locationType))
        locationpath: ((locationpath
